# SITE CONFIGURATION
baseurl: "/website-tmp"
url: "https://ssagheer532.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  title: Ahad Sagheer
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  description: "A person website and blog for Ahad Sagheer"

  header_text: >
     <p>I'm a software engineer with a BS Computer Science from Purdue University who thirsts for challenges and strives to solve any task. My favorite language is Java but I've also used Scala, Python, C, and C++. In the future I hope to one day lead a group programmers in creating real and impactful solutions!</p>
  header_text_feature_image:
  footer_text: >
   Ahad is a software engineer in the Washington DC Area

  rss: false
  email_address: syed.ahad.sagheer@gmail.com
  github: "ssagheer532"
  linkedin:  https://www.linkedin.com/in/ahadsagheer/
  youtube:

  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."


  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  post_navigation: false

paginate: 5
paginate_path: "tags/page:num"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
